//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderManagement_Service.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadedFile
    {
        public long DownloadedFileId { get; set; }
        public long ClientId { get; set; }
        public string FileName { get; set; }
        public string FolderPath { get; set; }
        public System.DateTime DownloadedOn { get; set; }
    }
}
