//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderManagement_Service.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscriber()
        {
            this.SubscriberAccomodities = new HashSet<SubscriberAccomodity>();
            this.Provinces = new HashSet<SubscriberProvince>();
            this.SubscriberRecipients = new HashSet<SubscriberRecipient>();
        }
    
        public long SubscriberId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string CompanyName { get; set; }
        public string ContactNumber { get; set; }
        public string MobileNumber { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> SubscriptionId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<int> FunctionId { get; set; }
        public Nullable<bool> IsNational { get; set; }
    
        public virtual Function Function { get; set; }
        public virtual SubscriptionType SubscriptionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriberAccomodity> SubscriberAccomodities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriberProvince> Provinces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriberRecipient> SubscriberRecipients { get; set; }
    }
}
