//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderManagement_Service.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionType
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int SubscriptionId { get; set; }
        public string SubscriptionTypeName { get; set; }
        public bool IsActive { get; set; }
    }
}
