//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderManagement_Service.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriberProvince
    {
        [System.ComponentModel.DataAnnotations.Key]
        public long SubscriberProvinceId { get; set; }
        public long SubscriberId { get; set; }
        public int ProvinceId { get; set; }
        public bool IsDeleted { get; set; }
    }
}
