//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderManagement_Service.DAL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TMSDBContext : DbContext
    {
        public TMSDBContext()
            : base("name=TMSDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<System.Data.Entity.ModelConfiguration.Conventions.PluralizingTableNameConvention>();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<DownloadedFile> DownloadedFiles { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Subscriber> Subscribers { get; set; }
        public virtual DbSet<SubscriberAccomodity> SubscriberAccomodities { get; set; }
        public virtual DbSet<SubscriberProvince> SubscriberProvinces { get; set; }
        public virtual DbSet<SubscriberRecipient> SubscriberRecipients { get; set; }
        public virtual DbSet<SubscriptionType> SubscriptionTypes { get; set; }
        public virtual DbSet<TenderMaster> TenderMasters { get; set; }
        public virtual DbSet<TenderMasterProvince> TenderMasterProvinces { get; set; }
    }
}
